business:
  phone: '+92 325 2333567'
  whatsapp: '923252333567'
custom_logo:
  'user/themes/kaffekos/images/logo/KAFFEKOS TISSUE DESIGN.pdf.png':
    name: 'KAFFEKOS TISSUE DESIGN.pdf.png'
    type: image/png
    size: 67225
    path: 'user/themes/kaffekos/images/logo/KAFFEKOS TISSUE DESIGN.pdf.png'
    url: '/kaffekos1/user/themes/kaffekos/images/logo/KAFFEKOS TISSUE DESIGN.pdf.png'
